# Generated by Django 3.0.2 on 2020-01-07 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LSTM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=250, unique=True)),
                ('path', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Samples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('path', models.CharField(max_length=250, unique=True)),
                ('lstm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='lstm.LSTM')),
            ],
        ),
    ]
