# Generated by Django 3.0.2 on 2020-01-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lstm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lstm',
            name='author',
            field=models.CharField(max_length=250),
        ),
    ]
