# Generated by Django 3.0.2 on 2020-01-07 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lstm', '0002_auto_20200107_1934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lstm',
            old_name='path',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='samples',
            name='path',
        ),
    ]
