# Generated by Django 3.0.2 on 2020-01-08 11:09

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('lstm', '0003_auto_20200107_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('lstms_trained', django_mysql.models.ListCharField(models.CharField(max_length=100), max_length=1000, size=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='samples',
            name='lstm',
        ),
        migrations.DeleteModel(
            name='LSTM',
        ),
        migrations.DeleteModel(
            name='Samples',
        ),
    ]
