from django.db import models
from django_mysql.models import ListCharField


class Author(models.Model):
    """ Each of these corresponds to a unique view """
    name = models.CharField(max_length=250, unique=True)
    lstms_trained = ListCharField(models.CharField(max_length=100), max_length=1000)

    def __str__(self):
        return self.name

#     class LSTM(models.Model):
#         """ LSTM saved models """
#         author = models.CharField(max_length=250, unique=False)
#         name = models.CharField(max_length=250, unique=True)
#
#         def __str__(self):
#             return self.name
#
#
#     class Samples(models.Model):
#         """ Sample files generated by a specific LSTM """
#         name = models.CharField(max_length=250, unique=True)
#         lstm = models.ForeignKey(LSTM, on_delete=models.CASCADE, related_name='samples')
#
#         def __str__(self):
#             return self.name
